<div class="mini-sidebar__wrapper ">
	<div class="mini-sidebar__arrow "></div>
	<a title = "Автобусные туры на море" href="<?php echo get_category_link(4)?>" class="mini-sidebar__link"><span class="mini-sidebar__link-text ">Автобусные туры на море </span><span class="mini-sidebar__link-icon" style="background-image: url(<?php echo get_stylesheet_directory_uri();?>/images/icon/sun-umbrella.svg)"></span></a>
	<a title = "Наши автобусы" href="<?php echo get_permalink(162)?>" class="mini-sidebar__link"><span class="mini-sidebar__link-text ">Наши автобусы </span><span class="mini-sidebar__link-icon" style="background-image: url(<?php echo get_stylesheet_directory_uri();?>/images/icon/bus-2.svg)"></span></a>
	<a title = "КУПИ ОНЛАЙН (ПРОЕЗД/ТУР)" href="<?php echo get_permalink(3168)?>" class="mini-sidebar__link"><span class="mini-sidebar__link-text ">КУПИ ОНЛАЙН (ПРОЕЗД/ТУР) </span><span class="mini-sidebar__link-icon" style="background-image: url(<?php echo get_stylesheet_directory_uri();?>/images/click-ol.svg)"></span></a>
	<a title = "Новогодние туры" href="<?php echo get_category_link(31)?>" class="mini-sidebar__link"><span class="mini-sidebar__link-text ">Новогодние туры</span><span class="mini-sidebar__link-icon" style="background-image: url(<?php echo get_stylesheet_directory_uri();?>/images/icon/new-tours.svg)"></span></a>
	<a title = "Майские туры 2019" href="<?php echo get_category_link(42)?>" class="mini-sidebar__link"><span class="mini-sidebar__link-text ">Майские туры 2020 </span><span class="mini-sidebar__link-icon" style="background-image: url(<?php echo get_stylesheet_directory_uri();?>/images/icon/spring.svg)"></span></a>		
	<a title = "Online-поиск тура" href="<?php echo get_permalink(1801)?>" class="mini-sidebar__link"><span class="mini-sidebar__link-text ">Online-поиск тура</span><span class="mini-sidebar__link-icon" style="background-image: url(<?php echo get_stylesheet_directory_uri();?>/images/icon/online.svg)"></span></a>
	<a title = "Визовый центр" href="<?php echo get_permalink(2645)?>" class="mini-sidebar__link"><span class="mini-sidebar__link-text ">Визовый центр</span><span class="mini-sidebar__link-icon" style="background-image: url(<?php echo get_stylesheet_directory_uri();?>/images/icon/passport.svg)"></span></a>
	<a title = "Вход для турагентов" href="<?php echo get_permalink(12)?>" class="mini-sidebar__link"><span class="mini-sidebar__link-text ">Вход для турагентов</span><span class="mini-sidebar__link-icon" style="background-image: url(<?php echo get_stylesheet_directory_uri();?>/images/icon/autorization.svg)"></span></a>
</div>